on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vnmacr.azurecr.io
        username: ${{secrets.acr_vnmacr_username}}
        password: ${{secrets.acr_vnmacr_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/./" -f  "./" -t vnmacr.azurecr.io/vnmaks165c:${{github.sha}}
        docker push vnmacr.azurecr.io/vnmaks165c:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_vnmaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vnmaksb2e5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vnmaksb2e5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vnmaksb2e5
        container-registry-url: vnmacr.azurecr.io
        container-registry-username: ${{secrets.acr_vnmacr_username}}
        container-registry-password: ${{secrets.acr_vnmacr_password}}
        secret-name: vnmaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vnmaksb2e5
        manifests: |
          manifests/deployment-65f0.yml
          manifests/service-65f0.yml
        images: |
          vnmacr.azurecr.io/vnmaks165c:${{github.sha}}
        imagepullsecrets: |
          vnmaksdockerauth